# Generated by Django 3.0.6 on 2020-05-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='douban_url',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
