# Generated by Django 3.0.6 on 2020-05-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200518_0734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translation',
            options={'verbose_name_plural': 'translations'},
        ),
        migrations.RenameField(
            model_name='translation',
            old_name='translation',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='book',
            name='url',
        ),
        migrations.AddField(
            model_name='book',
            name='link',
            field=models.URLField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.CharField(default='Reviewer ID', max_length=60),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='translation',
            name='translator',
            field=models.CharField(max_length=60),
        ),
    ]
