# Generated by Django 3.0.6 on 2020-05-18 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200518_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='book',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='en',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='zh',
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_sentence', models.TextField(max_length=1000)),
                ('recommended_trans', models.TextField(max_length=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
            options={
                'verbose_name_plural': 'sources',
            },
        ),
        migrations.AddField(
            model_name='translation',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Source'),
        ),
    ]
